version: '3.8'

services:
  db:
    image: 'postgres:latest'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      - db
    ports:
      - "${PORT:-3000}:3000"
    working_dir: /usr/src/app
    command: >
      sh -c "npx prisma generate && npm run start:docker"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
